name: Build and Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --icon assets/favicon.png --add-data assets:assets genome.py -y
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          directory: dist
          command: cp -r assets dist/genome && mv .env.example dist/genome/.env
          filename: genome.exe.zip
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/genome.exe.zip
          tag: ${{ github.ref }}
          asset_name: "genome_${{ matrix.os }}.zip"
