name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish for ${{ matrix.os }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --add-data assets:assets genome.py
      - uses: actions/upload-artifact@v3
        with:
          name: genome (${{ matrix.os }} ${{ matrix.python-version }})
          path: dist/*
